theme: jekyll-theme-hacker
title: secğŸ‘¨â€ğŸ’»fortress:~#
description: Defensive By Offensive!.
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
