theme: jekyll-theme-hacker
title: sixthğŸ‘¨ğŸ¾â€ğŸ’»sensei:~#
description: Security is art!
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
