theme: jekyll-theme-hacker
title: secğŸ‘¨â€ğŸ’»fortress:~$
description: Offensive for Defensive!.
url: <a href="https://www.buymeacoffee.com/Secfortress"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me an OSCP&emoji=&slug=Secfortress&button_colour=FFDD00&font_colour=000000&font_family=Arial&outline_colour=000000&coffee_colour=ffffff" /></a>
show_downloads: false
show_repo: false

safe: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  
gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

<a href="https://www.buymeacoffee.com/Secfortress"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me an OSCP&emoji=&slug=Secfortress&button_colour=FFDD00&font_colour=000000&font_family=Arial&outline_colour=000000&coffee_colour=ffffff" /></a>
